Doc: Replay attack issue
cosmos/ethermint pull request #728
Opened 2021-01-18 19:49 UTC by freddyli7

The document update regarding to transaction replay attack issue.

2021-01-21 16:17 UTC, noot commented on docs/basics/notice.md
> +Given the fact that Ethermint uses the same transaction signature pattern and the type of chainIDEpoch for Ethereum compatibility,
maybe reword to say "Given the fact that Ethermint uses the same transaction signature format as Ethereum for compatibility with Ethereum tooling, and Ethermint's  `chainIDEpoch` corresponds to the chain ID on Ethereum, any valid transaction..."

2021-01-25 20:45 UTC, araskachoi commented on docs/basics/notice.md
> +any valid transaction that is able to broadcast to Ethereum is also able to broadcast to Ethermint, and vice versa, which could lead to the Transaction Replay Attack if Ethermint starts the network b
"any valid transaction that is able to be broadcasted to Ethereum is also able to be broadcasted to Ethermint"

2021-01-25 20:47 UTC, araskachoi commented on docs/basics/notice.md
> +any valid transaction that is able to broadcast to Ethereum is also able to broadcast to Ethermint, and vice versa, which could lead to the Transaction Replay Attack if Ethermint starts the network b
-> "... could lead to a transaction replay attack..."

-> "... if Ethermint is initiated using a reserved chainID according to EIP155."

2021-01-25 20:48 UTC, araskachoi requested changes
looks good, please make the changes and will approve!

2021-01-25 20:48 UTC, araskachoi commented on docs/basics/notice.md
> +To prevent this issue, simply choose a different chainID other than [chainIDs that are reserved for Ethereum](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md#list-of-chain-ids).
"To prevent this issue, please choose a chainID that does not conflict with any of these [reserved ChainIDs](link...)"

2021-03-19 00:07 UTC, closed without merging